# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ssevova/GlobalCorrelator/pulsar_devkit/simple_examples/minimal_HLSArray_BRAM_ILA/top/top.srcs/sources_1/ip/simple_algo_array_hw_0/simple_algo_array_hw_0.xci
# IP: The module: 'simple_algo_array_hw_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ssevova/GlobalCorrelator/pulsar_devkit/simple_examples/minimal_HLSArray_BRAM_ILA/top/top.srcs/sources_1/ip/simple_algo_array_hw_0/constraints/simple_algo_array_hw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_algo_array_hw_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ssevova/GlobalCorrelator/pulsar_devkit/simple_examples/minimal_HLSArray_BRAM_ILA/top/top.srcs/sources_1/ip/simple_algo_array_hw_0/simple_algo_array_hw_0.xci
# IP: The module: 'simple_algo_array_hw_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ssevova/GlobalCorrelator/pulsar_devkit/simple_examples/minimal_HLSArray_BRAM_ILA/top/top.srcs/sources_1/ip/simple_algo_array_hw_0/constraints/simple_algo_array_hw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_algo_array_hw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
